### ISSUE TITLE
Don't know how to build task 'assets:precompile:primary'

### ISSUE THREAD

**Issue by greyblake** [jipiboily/monologue#187]
## Description

I added monologue to Gemfile, ran `bundle install`.

Now on attempt to run any of rake tasks I got this error:

```
 bundle exec rake monologue:install:migrations
rake aborted!
Don't know how to build task 'assets:precompile:primary'
/home/blake/.rvm/gems/ruby-2.0.0-p353@bf_clients/gems/tinymce-rails-3.5.6/lib/tasks/tinymce-assets.rake:1:in `<top (required)>'
/home/blake/.rvm/gems/ruby-2.0.0-p353@bf_clients/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:223:in `load'
/home/blake/.rvm/gems/ruby-2.0.0-p353@bf_clients/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:223:in `block in load'
/home/blake/.rvm/gems/ruby-2.0.0-p353@bf_clients/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/blake/.rvm/gems/ruby-2.0.0-p353@bf_clients/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:223:in `load'
/home/blake/.rvm/gems/ruby-2.0.0-p353@bf_clients/gems/railties-4.0.1/lib/rails/engine.rb:641:in `block in run_tasks_blocks'
/home/blake/.rvm/gems/ruby-2.0.0-p353@bf_clients/gems/railties-4.0.1/lib/rails/engine.rb:641:in `each'
/home/blake/.rvm/gems/ruby-2.0.0-p353@bf_clients/gems/railties-4.0.1/lib/rails/engine.rb:641:in `run_tasks_blocks'
/home/blake/.rvm/gems/ruby-2.0.0-p353@bf_clients/gems/railties-4.0.1/lib/rails/application.rb:243:in `block in run_tasks_blocks'
/home/blake/.rvm/gems/ruby-2.0.0-p353@bf_clients/gems/railties-4.0.1/lib/rails/engine/railties.rb:17:in `each'
/home/blake/.rvm/gems/ruby-2.0.0-p353@bf_clients/gems/railties-4.0.1/lib/rails/engine/railties.rb:17:in `each'
/home/blake/.rvm/gems/ruby-2.0.0-p353@bf_clients/gems/railties-4.0.1/lib/rails/application.rb:243:in `run_tasks_blocks'
/home/blake/.rvm/gems/ruby-2.0.0-p353@bf_clients/gems/railties-4.0.1/lib/rails/engine.rb:446:in `load_tasks'
/home/blake/.rvm/gems/ruby-2.0.0-p353@bf_clients/gems/railties-4.0.1/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/blake/poligon/rails_blog_engine/theblog/Rakefile:6:in `<top (required)>'
(See full trace by running task with --trace)
```
## Environment
- ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-linux]
- Rails 4.0.1

**Comment by vysogot** [comment]
Well, it's July 2015 and it's still an issue with Rails 4.2.2. I must say, +1 for "blogo" which works like a charm.

**Comment by vinhnglx** [comment]
@vysogot 

just FYI. I was run monologue on Rails 4.2.4. Here is my configure:

```ruby
# Gemfile
# Downgrade sass-rails from 5.0 to 4.0.0
gem 'sass-rails', '~> 4.0.0'

# Downgrade coffee-rails from 4.1.0 to 4.0.0
gem 'coffee-rails', '~> 4.0.0'

# Specify version for monologue
gem 'monologue', '~> 0.4.1'

# Fix routing error: The controller-level `respond_to' feature has been extracted to the `responders` gem
gem 'responders', '~> 2.0'
```

Config assets precompile for social_foundicons fonts in `config/initializers/assets.rb`

```ruby
# config/initializers/assets.rb

Rails.application.config.assets.precompile += %w( monologue/foundation_icons/social_foundicons.eot )
Rails.application.config.assets.precompile += %w( monologue/foundation_icons/social_foundicons.woff )
Rails.application.config.assets.precompile += %w( monologue/foundation_icons/social_foundicons.ttf )
```

And, now it's work well

![monologue](https://cloud.githubusercontent.com/assets/1997137/10870212/cad177dc-80f7-11e5-9d97-747f3e0edce4.png)
