### ISSUE TITLE
undefined method 'config' for Monologue:Module when deploying to AWS w/ Capistrano 3

### ISSUE THREAD

**Issue by travisdmathis** [jipiboily/monologue#254]
NoMethodError: undefined method `config' for Monologue:Module
/home/deploy/imagerelay-brand/releases/20150406203450/config/initializers/monologue.rb:1:in `<top (required)>'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:652:in `block in load_config_initializer'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:651:in `load_config_initializer'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `each'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `block in <class:Engine>'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
/home/deploy/imagerelay-brand/releases/20150406203450/config/environment.rb:5:in `<top (required)>'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:443:in `block in run_tasks_blocks'
/home/deploy/imagerelay-brand/shared/bundle/ruby/2.2.0/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'

**Comment by travisdmathis** [comment]
this was resolved with some permission fixes
