### ISSUE TITLE
rails 4.2.4 TypeError - no implicit conversion of Fixnum into String

### ISSUE THREAD

**Issue by MicFin** [jipiboily/monologue#291]
Updated to rails 4.2.4 and hitting major issues with uploading an image in ckeditor.

```
method=POST path=/ckeditor/pictures format=html controller=ckeditor/pictures action=create status=500 duration=138.47 view=0.00 db=6.95 params={"upload"=>#<ActionDispatch::Http::UploadedFile:0x007f841f732530 @tempfile=#<Tempfile:/var/folders/4_/f7xs_fxs3qs0kd5hfl6w2cdr0000gn/T/RackMultipart20160821-30171-anw8pv.jpg>, @original_filename="gluten_question.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"upload\"; filename=\"gluten_question.jpg\"\r\nContent-Type: image/jpeg\r\n">, "ckCsrfToken"=>"0NQGVepAbffIYHH8r18RK1C7A3htweDc7AQ1yUzi", "CKEditor"=>"post_content", "CKEditorFuncNum"=>"1", "langCode"=>"en"} time=2016-08-21 17:02:14 -0400

TypeError - no implicit conversion of Fixnum into String:
  cocaine (0.5.8) lib/cocaine/command_line/runners/process_runner.rb:30:in `spawn'
  cocaine (0.5.8) lib/cocaine/command_line/runners/process_runner.rb:20:in `call'
  cocaine (0.5.8) lib/cocaine/command_line.rb:147:in `execute'
  cocaine (0.5.8) lib/cocaine/command_line.rb:74:in `run'
  ckeditor (4.1.6) lib/ckeditor/utils/content_type_detector.rb:33:in `content_type_from_file_command'
  ckeditor (4.1.6) lib/ckeditor/utils/content_type_detector.rb:21:in `detect'
  ckeditor (4.1.6) lib/ckeditor/backend/carrierwave.rb:40:in `extract_content_type'
  carrierwave (0.10.0) lib/carrierwave/uploader/processing.rb:84:in `block in process!'
  carrierwave (0.10.0) lib/carrierwave/uploader/processing.rb:76:in `process!'
  carrierwave (0.10.0) lib/carrierwave/uploader/callbacks.rb:18:in `block in with_callbacks'
  carrierwave (0.10.0) lib/carrierwave/uploader/callbacks.rb:18:in `with_callbacks'
  carrierwave (0.10.0) lib/carrierwave/uploader/cache.rb:122:in `cache!'
  carrierwave (0.10.0) lib/carrierwave/mount.rb:329:in `cache'
  carrierwave (0.10.0) lib/carrierwave/mount.rb:163:in `data='
  carrierwave (0.10.0) lib/carrierwave/orm/activerecord.rb:39:in `data='
  ckeditor (4.1.6) lib/ckeditor/asset_response.rb:10:in `initialize'
  ckeditor (4.1.6) app/controllers/ckeditor/application_controller.rb:11:in `respond_with_asset'
  ckeditor (4.1.6) app/controllers/ckeditor/pictures_controller.rb:15:in `create'
  actionpack (4.2.4) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.4) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.4) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.4) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  activesupport (4.2.4) lib/active_support/callbacks.rb:298:in `block in halting_and_conditional'
  activesupport (4.2.4) lib/active_support/callbacks.rb:497:in `block in around'
  activesupport (4.2.4) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.4) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.4) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.4) lib/action_view/rendering.rb:30:in `process'
  rack-mini-profiler (0.10.1) lib/mini_profiler/profiling_methods.rb:102:in `block in profile_method'
  actionpack (4.2.4) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.4) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.4) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:821:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.4) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:821:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  bullet (5.3.0) lib/bullet/rack.rb:12:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/rack/developer_mode.rb:48:in `traced_call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  browser_details (0.0.6) lib/browser_details.rb:59:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  route_downcaser (1.1.4) lib/route_downcaser/downcase_route_middleware.rb:46:in `_call'
  route_downcaser (1.1.4) lib/route_downcaser/downcase_route_middleware.rb:9:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  remotipart (1.2.1) lib/remotipart/middleware.rb:27:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/flash.rb:260:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activerecord (4.2.4) lib/active_record/query_cache.rb:36:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  airbrake (5.4.4) lib/airbrake/rack/middleware.rb:22:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activerecord (4.2.4) lib/active_record/migration.rb:377:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:56:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack-contrib (1.4.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/headers.rb:16:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  lograge (0.3.4) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  request_store (1.3.1) lib/request_store/middleware.rb:9:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack-mini-profiler (0.10.1) lib/mini_profiler/profiler.rb:278:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/Mike/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /Users/Mike/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /Users/Mike/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

/Users/Mike/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/uri/generic.rb:1501: [BUG] Segmentation fault at 0x00000000000018
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:                    
     * ~/Library/Logs/CrashReporter                                         
     * /Library/Logs/CrashReporter                                          
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.     

-- Control frame information -----------------------------------------------
c:0018 p:0074 s:0095 e:000092 METHOD /Users/Mike/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/uri/generic.rb:1501
c:0017 p:0049 s:0083 e:000082 METHOD /Users/Mike/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1053
c:0016 p:0015 s:0080 e:000079 METHOD /Users/Mike/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1038
c:0015 p:0008 s:0077 e:000076 METHOD /Users/Mike/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:869
c:0014 p:0008 s:0064 e:000063 METHOD /Users/Mike/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:863
c:0013 p:0039 s:0061 e:000060 METHOD /Users/Mike/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:852
c:0012 p:0020 s:0058 e:000057 METHOD /Users/Mike/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1398
c:0011 p:0015 s:0051 e:000050 BLOCK  /Users/Mike/.rvm/gems/ruby-2.3.1/gems/rack-mini-profiler-0.10.1/lib/patches/net_patches.rb:7
c:0010 p:0096 s:0049 e:000048 METHOD /Users/Mike/.rvm/gems/ruby-2.3.1/gems/rack-mini-profiler-0.10.1/lib/mini_profiler/profiling_methods.rb:37
c:0009 p:0045 s:0042 e:000041 METHOD /Users/Mike/.rvm/gems/ruby-2.3.1/gems/rack-mini-profiler-0.10.1/lib/patches/net_patches.rb:6
c:0008 p:0020 s:0036 e:000035 BLOCK  /Users/Mike/.rvm/gems/ruby-2.3.1/gems/newrelic_rpm-3.16.1.320/lib/new_relic/agent/instrumentation/net.rb:27
c:0007 p:0035 s:0034 e:000033 METHOD /Users/Mike/.rvm/gems/ruby-2.3.1/gems/newrelic_rpm-3.16.1.320/lib/new_relic/agent.rb:428
c:0006 p:0017 s:0031 e:000030 BLOCK  /Users/Mike/.rvm/gems/ruby-2.3.1/gems/newrelic_rpm-3.16.1.320/lib/new_relic/agent/instrumentation/net.rb:26
c:0005 p:0070 s:0029 e:000028 METHOD /Users/Mike/.rvm/gems/ruby-2.3.1/gems/newrelic_rpm-3.16.1.320/lib/new_relic/agent/cross_app_tracing.rb:48
c:0004 p:0044 s:0021 e:000020 METHOD /Users/Mike/.rvm/gems/ruby-2.3.1/gems/newrelic_rpm-3.16.1.320/lib/new_relic/agent/instrumentation/net.rb:23
c:0003 p:0092 s:0014 e:000013 METHOD /Users/Mike/.rvm/gems/ruby-2.3.1/gems/airbrake-ruby-1.4.6/lib/airbrake-ruby/sync_sender.rb:37
c:0002 p:0020 s:0005 e:000004 BLOCK  /Users/Mike/.rvm/gems/ruby-2.3.1/gems/airbrake-ruby-1.4.6/lib/airbrake-ruby/async_sender.rb:104 [FINISH]
c:0001 p:---- s:0002 e:000001 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/Users/Mike/.rvm/gems/ruby-2.3.1/gems/airbrake-ruby-1.4.6/lib/airbrake-ruby/async_sender.rb:104:in `block in spawn_worker'
/Users/Mike/.rvm/gems/ruby-2.3.1/gems/airbrake-ruby-1.4.6/lib/airbrake-ruby/sync_sender.rb:37:in `send'
/Users/Mike/.rvm/gems/ruby-2.3.1/gems/newrelic_rpm-3.16.1.320/lib/new_relic/agent/instrumentation/net.rb:23:in `request_with_newrelic_trace'
/Users/Mike/.rvm/gems/ruby-2.3.1/gems/newrelic_rpm-3.16.1.320/lib/new_relic/agent/cross_app_tracing.rb:48:in `tl_trace_http_request'
/Users/Mike/.rvm/gems/ruby-2.3.1/gems/newrelic_rpm-3.16.1.320/lib/new_relic/agent/instrumentation/net.rb:26:in `block in request_with_newrelic_trace'
/Users/Mike/.rvm/gems/ruby-2.3.1/gems/newrelic_rpm-3.16.1.320/lib/new_relic/agent.rb:428:in `disable_all_tracing'
/Users/Mike/.rvm/gems/ruby-2.3.1/gems/newrelic_rpm-3.16.1.320/lib/new_relic/agent/instrumentation/net.rb:27:in `block (2 levels) in request_with_newrelic_trace'
/Users/Mike/.rvm/gems/ruby-2.3.1/gems/rack-mini-profiler-0.10.1/lib/patches/net_patches.rb:6:in `request_with_mini_profiler'
/Users/Mike/.rvm/gems/ruby-2.3.1/gems/rack-mini-profiler-0.10.1/lib/mini_profiler/profiling_methods.rb:37:in `step'
/Users/Mike/.rvm/gems/ruby-2.3.1/gems/rack-mini-profiler-0.10.1/lib/patches/net_patches.rb:7:in `block in request_with_mini_profiler'
/Users/Mike/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1398:in `request'
/Users/Mike/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:852:in `start'
/Users/Mike/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
/Users/Mike/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:869:in `connect'
/Users/Mike/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1038:in `proxy?'
/Users/Mike/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1053:in `proxy_uri'
/Users/Mike/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/uri/generic.rb:1501:in `find_proxy'

-- Machine register context ------------------------------------------------
 rax: 0x00000000000000c9 rbx: 0x00007f8412858020 rcx: 0x00007f841226e010
 rdx: 0xfffffffffffffff8 rdi: 0x0000000000000000 rsi: 0x0000000000000000
 rbp: 0x000070000081cb20 rsp: 0x000070000081c7e0  r8: 0x00007f8416b14828
  r9: 0x00007f841226e948 r10: 0x0000000000000000 r11: 0x000000000c13ee3c
 r12: 0x0000000000000000 r13: 0x00000001070a5b80 r14: 0x00007f8404aeca80
 r15: 0x00007f84110448f0 rip: 0x0000000103beb491 rfl: 0x0000000000010246

-- C level backtrace information -------------------------------------------
0   libruby.2.3.0.dylib                 0x0000000103c0cb04 rb_vm_bugreport + 388
1   libruby.2.3.0.dylib                 0x0000000103aa452a rb_bug_context + 490
2   libruby.2.3.0.dylib                 0x0000000103b7a7b3 sigsegv + 83
3   libsystem_platform.dylib            0x00007fff9554d52a _sigtramp + 26
4   libruby.2.3.0.dylib                 0x0000000103beb491 vm_exec_core + 11841
5   ???                                 0x0000000000000000 0x0 + 0

-- Other runtime information -----------------------------------------------

* Loaded script: bin/rails

* Loaded features:
```

**Comment by jipiboily** [comment]
Yeah, a lot of broken things. Sorry about that. Trying to get back on track. Paying $100 to anyone who puts Monologue back on track with Rails 5 support. Closing but see https://github.com/jipiboily/monologue/issues/314
