### ISSUE TITLE
bin/rake monologue:install:migrations thrown an errors 

### ISSUE THREAD

**Issue by rahmatullah5** [jipiboily/monologue#319]
When i'm execute `bin/rake monologue:install:migrations` it give me  :

`/Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/bootstrap-sass-3.3.7/lib/bootstrap-sass/version.rb:2: warning: already initialized constant Bootstrap::VERSION
/Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/bootstrap-4.0.0.beta2.1/lib/bootstrap/version.rb:2: warning: previous definition of VERSION was here
/Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/bootstrap-sass-3.3.7/lib/bootstrap-sass/version.rb:3: warning: already initialized constant Bootstrap::BOOTSTRAP_SHA
/Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/bootstrap-4.0.0.beta2.1/lib/bootstrap/version.rb:3: warning: previous definition of BOOTSTRAP_SHA was here
/Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:79:in `check_via': You should not use the `match` method in your router without specifying an HTTP method.
If you want to expose your action to both GET and POST, add `via: [:get, :post]` option.
If you want to expose your action to GET, use `get` in the router:
  Instead of: match "controller#action"
  Do: get "controller#action" (ArgumentError)
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:1841:in `map_match'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:1597:in `match'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/monologue-0.2.0/config/routes.rb:3:in `block in <top (required)>'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:629:in `instance_exec'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:629:in `block in with_default_scope'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:866:in `scope'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:628:in `with_default_scope'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:424:in `eval_block'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:408:in `draw'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/monologue-0.2.0/config/routes.rb:1:in `<top (required)>'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:55:in `block in load_paths'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:55:in `each'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:55:in `load_paths'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:18:in `reload!'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:41:in `block in updater'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/file_update_checker.rb:81:in `execute'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:42:in `updater'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:31:in `execute_if_updated'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/application/finisher.rb:128:in `block in <module:Finisher>'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /Users/fourtyonestudio/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /Users/fourtyonestudio/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/fourtyonestudio/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/fourtyonestudio/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/fourtyonestudio/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /Users/fourtyonestudio/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /Users/fourtyonestudio/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/fourtyonestudio/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /Users/fourtyonestudio/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
	from /Users/fourtyonestudio/Documents/Workspace/personal/me/config/environment.rb:5:in `<top (required)>'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:102:in `preload'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/fourtyonestudio/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/fourtyonestudio/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/fourtyonestudio/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'`

Here is my gemfile : 

gem 'rails', '~> 5.1.4'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.7'
gem 'sass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'webpacker'

gem 'coffee-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'

gem 'bootstrap'
gem 'twitter-bootstrap-rails', :git => 'git://github.com/seyhunak/twitter-bootstrap-rails.git'
gem 'bootstrap-sass'
gem 'jquery-rails'
gem 'slim-rails'
gem 'simple_form'

gem 'monologue'
gem 'railties'

group :development, :test do

  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]

  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
  gem 'faker', :git => 'git://github.com/stympy/faker.git', :branch => 'master'
  gem 'dotenv-rails'
end

group :development do

  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'

  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

**Comment by jipiboily** [comment]
Monologue didn't receive a lot of love in the last few months, even years. I have no idea if it works with Rails 5.1.

I am not using it anymore myself and it's not really maintained anymore.

That said, if you find the solution, feel free to send a PR :)

Sorry about that.

**Comment by rahmatullah5** [comment]
Hi @jipiboily thanks for the information , can you give me an advice/recomendation about blog engine beside monologue ?

**Comment by jipiboily** [comment]
I wish I could. I have no idea as while I am working with Rails
day to day still, I haven't done any website or ecommerce store
with Rails for years. Maybe have a look at Refinery CMS?

Good luck!

JP Boily

Founder @ Metrics Watch 
( https://metricswatch.com/?utm_source=email&utm_medium=gmail-signature )
 (and a new SaaS, see below) - Email Reports & Real-time Alerts
for Google Analytics

On November 17, 2017 at 7:24 AM, Muhammad Rahmatullah
(notifications@github.com) wrote:

Hi @jipiboily ( https://github.com/jipiboily ) thanks for the
information , can you give me an advice/recomendation about blog
engine beside monologue ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub 
( https://github.com/jipiboily/monologue/issues/319#issuecomment-345230548 )
, or mute the thread
